// export const CREATE_PERSON = "REPORT/CREATE_PERSON"
// export const FAKE_PERSONS = "REPORT/FAKE_PERSONS"
// export const ADD_REASONS = "REPORT/ADD_REASONS"
// export const SHOW_POPUP = "APP/SHOW_POPUP"
// export const HIDE_POPUP = "APP/HIDE_POPUP"

export enum ActionType {
    GET_PERSON = "GETPERSON",
    FAKE_PERSONS = "FAKE_PERSONS",
    ADD_REASONS = "ADD_REASONS",
    SHOW_POPUP = "APP/SHOW_POPUP",
    HIDE_POPUP = "APP/HIDE_POPUP"
}